[build]
  publish = "build"
  command = "npm run build && cp public/_headers build/_headers"
  functions = "netlify/functions"

# Admin path bypass
[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat"
  status = 200

# Redirect all other routes to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
# Make sure the admin path works correctly
[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# Add redirect for the refresh-data API endpoint
[[redirects]]
  from = "/api/refresh-data"
  to = "/.netlify/functions/refresh-data"
  status = 200
  
# Add header for content security policy
[[headers]]
  for = "/*"
    [headers.values]
    Content-Security-Policy = "default-src 'self' https://identity.netlify.com https://unpkg.com; script-src 'self' 'unsafe-inline' https://identity.netlify.com https://unpkg.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://randomuser.me https://*.netlify.app https://*.openstreetmap.org; connect-src 'self' https://api.netlify.com; frame-src 'self' https://*.openstreetmap.org;"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "same-origin"