backend:
  name: git-gateway
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  # ACHIEVEMENTS
  - name: "achievements"
    label: "Achievements"
    folder: "data/achievements"
    create: true
    fields:
      - { name: "id", label: "ID", widget: "string" }
      - { name: "title", label: "Title", widget: "string" }
      - { name: "description", label: "Description", widget: "text" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "venue", label: "Venue", widget: "string" }
      - { name: "category", label: "Category", widget: "select", options: ["competition", "innovation", "sustainability", "academic"] }
      - { name: "imageUrl", label: "Image", widget: "image", media_folder: "achievements" }
      - name: "additionalAwards"
        label: "Additional Awards"
        widget: "list"
        fields:
          - { name: "award", label: "Award", widget: "string" }

  # EVENTS
  - name: "events"
    label: "Events"
    folder: "data/events"
    create: true
    fields:
      - { name: "id", label: "ID", widget: "string" }
      - { name: "title", label: "Title", widget: "string" }
      - { name: "description", label: "Description", widget: "text" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "location", label: "Location", widget: "string" }
      - { name: "category", label: "Category", widget: "select", options: ["competition", "workshop", "expo", "team", "networking"] }
      - { name: "imageUrl", label: "Image", widget: "image" }
      - { name: "isUpcoming", label: "Is Upcoming?", widget: "boolean", default: true }
      - name: "results"
        label: "Results"
        widget: "list"
        fields:
          - { name: "position", label: "Position", widget: "string" }
          - { name: "team", label: "Team", widget: "string" }
          - name: "achievements"
            label: "Achievements"
            widget: "list"
            fields:
              - { name: "achievement", label: "Achievement", widget: "string" }
      - { name: "registrationLink", label: "Registration Link", widget: "string", required: false }
      - { name: "registrationDeadline", label: "Registration Deadline", widget: "datetime", required: false }

  # GALLERY
  - name: "gallery"
    label: "Gallery"
    folder: "data/gallery"
    create: true
    fields:
      - { name: "id", label: "ID", widget: "string" }
      - { name: "title", label: "Title", widget: "string" }
      - { name: "category", label: "Category", widget: "select", options: ["cars", "engineering", "competitions", "testing", "team", "academic"] }
      - { name: "type", label: "Type", widget: "select", options: ["image", "video"] }
      - { name: "url", label: "Media File", widget: "image", media_folder: "gallery" }
      - { name: "alt", label: "Alt Text", widget: "string", required: false }
      - { name: "thumbnail", label: "Thumbnail (for videos)", widget: "image", required: false }
      - { name: "description", label: "Description", widget: "text" }
      - { name: "date", label: "Date", widget: "datetime" }

  # MEMBERS
  - name: "members"
    label: "Team Members"
    folder: "data/members"
    create: true
    fields:
      - { name: "id", label: "ID", widget: "string" }
      - { name: "name", label: "Name", widget: "string" }
      - { name: "role", label: "Role", widget: "string" }
      - { name: "bio", label: "Bio", widget: "text" }
      - { name: "image_url", label: "Profile Photo", widget: "image", media_folder: "team" }
      - name: "social_links"
        label: "Social Links"
        widget: "object"
        fields:
          - { name: "linkedin", label: "LinkedIn", widget: "string", required: false }
          - { name: "twitter", label: "Twitter", widget: "string", required: false }
          - { name: "github", label: "GitHub", widget: "string", required: false }

  # MERCHANDISE
  - name: "merchandise"
    label: "Merchandise"
    folder: "data/merchandise"
    create: true
    fields:
      - { name: "id", label: "ID", widget: "string" }
      - { name: "name", label: "Name", widget: "string" }
      - { name: "description", label: "Description", widget: "text" }
      - { name: "price", label: "Price", widget: "number" }
      - { name: "category", label: "Category", widget: "select", options: ["apparel", "accessories", "collectibles"] }
      - { name: "imageUrl", label: "Product Image", widget: "image" }
      - name: "availableSizes"
        label: "Available Sizes"
        widget: "list"
        required: false
        fields:
          - { name: "size", label: "Size", widget: "string" }
      - { name: "stockQuantity", label: "Stock Quantity", widget: "number" }
      - { name: "featured", label: "Featured?", widget: "boolean", default: false }

  # NEWS
  - name: "news"
    label: "News"
    folder: "data/news"
    create: true
    fields:
      - { name: "id", label: "ID", widget: "string" }
      - { name: "title", label: "Title", widget: "string" }
      - { name: "content", label: "Content", widget: "markdown" }
      - { name: "summary", label: "Summary", widget: "text" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "author", label: "Author", widget: "string" }
      - { name: "category", label: "Category", widget: "string" }
      - { name: "imageUrl", label: "Featured Image", widget: "image" }
      - name: "tags"
        label: "Tags"
        widget: "list"
        fields:
          - { name: "tag", label: "Tag", widget: "string" }

  # PROJECTS
  - name: "projects"
    label: "Projects"
    folder: "data/projects"
    create: true
    fields:
      - { name: "id", label: "ID", widget: "string" }
      - { name: "title", label: "Title", widget: "string" }
      - { name: "description", label: "Description", widget: "text" }
      - { name: "status", label: "Status", widget: "select", options: ["In Progress", "Completed", "Planning"] }
      - { name: "start_date", label: "Start Date", widget: "datetime" }
      - { name: "end_date", label: "End Date", widget: "datetime", required: false }
      - { name: "image_url", label: "Project Image", widget: "image" }
      - name: "members"
        label: "Members"
        widget: "list"
        fields:
          - { name: "role", label: "Role", widget: "string" }
          - { name: "member_id", label: "Member ID", widget: "string" }

  # RACING JOURNEY
  - name: "racing_journey"
    label: "Racing Journey"
    folder: "data/racing-journey"
    create: true
    fields:
      - { name: "id", label: "ID", widget: "number" }
      - { name: "title", label: "Title", widget: "string" }
      - { name: "description", label: "Description", widget: "text" }
      - { name: "image", label: "Image", widget: "image" }
      - { name: "link", label: "Link", widget: "string" }

  # SPONSORS
  - name: "sponsors"
    label: "Sponsors"
    folder: "data/sponsors"
    create: true
    fields:
      - { name: "id", label: "ID", widget: "string" }
      - { name: "name", label: "Name", widget: "string" }
      - { name: "logo", label: "Logo", widget: "image", media_folder: "sponsors" }
      - { name: "tier", label: "Tier", widget: "select", options: ["platinum", "gold", "silver", "bronze", "partner"] }
      - { name: "website", label: "Website", widget: "string" }
      - { name: "description", label: "Description", widget: "text", required: false }
      - { name: "since", label: "Since", widget: "string" }

  # TEAM INFO (corrected single file configuration)
  - name: "team_info"
    label: "Team Info"
    files:
      - name: "team_info"
        label: "Team Information"
        file: "data/team-info.json"
        fields:
          - name: "welcome"
            label: "Welcome Section"
            widget: "object"
            fields:
              - { name: "title", label: "Title", widget: "string" }
              - name: "description"
                label: "Description"
                widget: "list"
                fields:
                  - { name: "paragraph", label: "Paragraph", widget: "text" }
              - { name: "logoImage", label: "Logo Image", widget: "image", media_folder: "logo" }
              - { name: "buttonText", label: "Button Text", widget: "string" }
              - { name: "buttonLink", label: "Button Link", widget: "string" }
          - name: "mission"
            label: "Mission Section"
            widget: "object"
            fields:
              - { name: "title", label: "Title", widget: "string" }
              - { name: "statement", label: "Statement", widget: "text" }
              - name: "values"
                label: "Values"
                widget: "list"
                fields:
                  - { name: "title", label: "Title", widget: "string" }
                  - { name: "description", label: "Description", widget: "text" }