backend:
  name: git-gateway
  branch: main
  repo: deepak-158/Vitian-formula-racing-official-website

# Editorial workflow (optional - enables the draft → review → publish workflow)
publish_mode: editorial_workflow

# Media and public folders
media_folder: "public/images"
public_folder: "/images"

# Collections define the structure for different content types
collections:
  - name: "data"
    label: "Site Data"
    files:
      - name: "members"
        label: "Team Members"
        file: "src/data/members.json"
        format: "json"
        fields:
          - label: "Members"
            name: "members"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "string" }
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Role", name: "role", widget: "string" }
              - { label: "Bio", name: "bio", widget: "text" }
              - { label: "Image", name: "image_url", widget: "image" }
              - label: "Social Links"
                name: "social_links"
                widget: "object"
                fields:
                  - { label: "LinkedIn", name: "linkedin", widget: "string", required: false }
                  - { label: "Twitter", name: "twitter", widget: "string", required: false }
                  - { label: "GitHub", name: "github", widget: "string", required: false }
      
      - name: "achievements"
        label: "Achievements"
        file: "src/data/achievements.json"
        format: "json"
        fields:
          - label: "Achievements"
            name: "achievements"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "string" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Date", name: "date", widget: "date" }
              - { label: "Venue", name: "venue", widget: "string" }
              - { label: "Category", name: "category", widget: "string" }
              - { label: "Image", name: "imageUrl", widget: "image" }
              - label: "Additional Awards"
                name: "additionalAwards"
                widget: "list"
                required: false
                field:
                  label: "Award"
                  name: "award"
                  widget: "string"

      - name: "events"
        label: "Events"
        file: "src/data/events.json"
        format: "json"
        fields:
          - label: "Events"
            name: "events"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "string" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Date", name: "date", widget: "date" }
              - { label: "Location", name: "location", widget: "string" }
              - { label: "Category", name: "category", widget: "string" }
              - { label: "Image", name: "imageUrl", widget: "image" }
              - { label: "Is Upcoming", name: "isUpcoming", widget: "boolean", default: true }
              - { label: "Registration Link", name: "registrationLink", widget: "string", required: false }
              - { label: "Registration Deadline", name: "registrationDeadline", widget: "date", required: false }
      
      - name: "gallery"
        label: "Gallery"
        file: "src/data/gallery.json"
        format: "json"
        fields:
          - label: "Gallery Items"
            name: "gallery"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "string" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Category", name: "category", widget: "string" }
              - { label: "Type", name: "type", widget: "select", options: ["image", "video"] }
              - { label: "URL", name: "url", widget: "image" }
              - { label: "Alt Text", name: "alt", widget: "string", required: false }
              - { label: "Thumbnail", name: "thumbnail", widget: "image", required: false }
              - { label: "Description", name: "description", widget: "text", required: false }
              - { label: "Date", name: "date", widget: "date" }
      
      - name: "merchandise"
        label: "Merchandise"
        file: "src/data/merchandise.json"
        format: "json"
        fields:
          - label: "Merchandise Items"
            name: "merchandise"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "string" }
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Price", name: "price", widget: "number" }
              - { label: "Category", name: "category", widget: "string" }
              - { label: "Image URL", name: "imageUrl", widget: "image" }
              - label: "Available Sizes"
                name: "availableSizes"
                widget: "list"
                required: false
                field:
                  label: "Size"
                  name: "size"
                  widget: "string"
              - { label: "Stock Quantity", name: "stockQuantity", widget: "number" }
              - { label: "Featured", name: "featured", widget: "boolean", default: false }
      
      - name: "racing-journey"
        label: "Racing Journey"
        file: "src/data/racing-journey.json"
        format: "json"
        fields:
          - label: "Journey Milestones"
            name: "racingJourney"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "number" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Link", name: "link", widget: "string", required: false }
      
      - name: "sponsors"
        label: "Sponsors"
        file: "src/data/sponsors.json"
        format: "json"
        fields:
          - label: "Sponsors"
            name: "sponsors"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "string" }
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Logo", name: "logo", widget: "image" }
              - label: "Tier"
                name: "tier"
                widget: "select"
                options: ["platinum", "gold", "silver", "bronze", "partner"]
              - { label: "Website", name: "website", widget: "string" }
              - { label: "Description", name: "description", widget: "text", required: false }
              - { label: "Since", name: "since", widget: "string", required: false }
      
      - name: "team-info"
        label: "Team Info"
        file: "src/data/team-info.json"
        format: "json"
        fields:
          - label: "Welcome Section"
            name: "welcome"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - label: "Description"
                name: "description"
                widget: "list"
                field:
                  label: "Description Paragraph"
                  name: "paragraph"
                  widget: "text"
              - { label: "Logo Image", name: "logoImage", widget: "image" }
              - { label: "Button Text", name: "buttonText", widget: "string" }
              - { label: "Button Link", name: "buttonLink", widget: "string" }
          - label: "Mission Section"
            name: "mission"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Mission Statement", name: "statement", widget: "text" }
              - label: "Values"
                name: "values"
                widget: "list"
                fields:
                  - { label: "Title", name: "title", widget: "string" }
                  - { label: "Description", name: "description", widget: "text" }