backend:
  name: test-repo

media_folder: "public/images"
public_folder: "/images"

# Simplified collections for development and quick testing
collections:
  # ACHIEVEMENTS
  - name: "achievements"
    label: "🏆 Achievements"
    folder: "data/achievements"
    create: true
    slug: "{{id}}"
    fields:
      - { name: "id", label: "ID", widget: "string", hint: "Unique identifier (e.g., ach_2025_001)" }
      - { name: "title", label: "Title", widget: "string" }
      - { name: "description", label: "Description", widget: "text" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "venue", label: "Venue", widget: "string" }
      - { name: "category", label: "Category", widget: "select", options: ["competition", "innovation", "sustainability", "academic"] }
      - { name: "imageUrl", label: "Image", widget: "image", required: false }

  # EVENTS
  - name: "events"
    label: "📅 Events"
    folder: "data/events"
    create: true
    slug: "{{id}}"
    fields:
      - { name: "id", label: "ID", widget: "string", hint: "Unique identifier (e.g., evt_2025_001)" }
      - { name: "title", label: "Title", widget: "string" }
      - { name: "description", label: "Description", widget: "text" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "location", label: "Location", widget: "string" }
      - { name: "category", label: "Category", widget: "select", options: ["competition", "workshop", "expo", "team", "networking"] }
      - { name: "imageUrl", label: "Image", widget: "image", required: false }
      - { name: "isUpcoming", label: "Is Upcoming?", widget: "boolean", default: true }

  # GALLERY
  - name: "gallery"
    label: "📸 Gallery"
    folder: "data/gallery"
    create: true
    slug: "{{id}}"
    fields:
      - { name: "id", label: "ID", widget: "string", hint: "Unique identifier (e.g., gal_2025_001)" }
      - { name: "title", label: "Title", widget: "string" }
      - { name: "category", label: "Category", widget: "select", options: ["cars", "engineering", "competitions", "testing", "team", "academic"] }
      - { name: "type", label: "Type", widget: "select", options: ["image", "video"] }
      - { name: "url", label: "Media File", widget: "image" }
      - { name: "description", label: "Description", widget: "text" }
      - { name: "date", label: "Date", widget: "datetime" }

  # MEMBERS
  - name: "members"
    label: "👥 Team Members"
    folder: "data/members"
    create: true
    slug: "{{id}}"
    fields:
      - { name: "id", label: "ID", widget: "string", hint: "Unique identifier (e.g., mem_2025_001)" }
      - { name: "name", label: "Name", widget: "string" }
      - { name: "role", label: "Role", widget: "string" }
      - { name: "bio", label: "Bio", widget: "text" }
      - { name: "image_url", label: "Profile Photo", widget: "image", required: false }

  # MERCHANDISE
  - name: "merchandise"
    label: "🛍️ Merchandise"
    folder: "data/merchandise"
    create: true
    slug: "{{id}}"
    fields:
      - { name: "id", label: "ID", widget: "string", hint: "Unique identifier (e.g., mer_2025_001)" }
      - { name: "name", label: "Name", widget: "string" }
      - { name: "description", label: "Description", widget: "text" }
      - { name: "price", label: "Price", widget: "number" }
      - { name: "category", label: "Category", widget: "select", options: ["apparel", "accessories", "collectibles"] }
      - { name: "imageUrl", label: "Product Image", widget: "image", required: false }
      - { name: "stockQuantity", label: "Stock Quantity", widget: "number" }
      - { name: "featured", label: "Featured?", widget: "boolean", default: false }

  # NEWS
  - name: "news"
    label: "📰 News"
    folder: "data/news"
    create: true
    slug: "{{id}}"
    fields:
      - { name: "id", label: "ID", widget: "string", hint: "Unique identifier (e.g., new_2025_001)" }
      - { name: "title", label: "Title", widget: "string" }
      - { name: "content", label: "Content", widget: "markdown" }
      - { name: "summary", label: "Summary", widget: "text" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "author", label: "Author", widget: "string" }
      - { name: "category", label: "Category", widget: "string" }
      - { name: "imageUrl", label: "Featured Image", widget: "image", required: false }

  # PROJECTS
  - name: "projects"
    label: "🔧 Projects"
    folder: "data/projects"
    create: true
    slug: "{{id}}"
    fields:
      - { name: "id", label: "ID", widget: "string", hint: "Unique identifier (e.g., prj_2025_001)" }
      - { name: "title", label: "Title", widget: "string" }
      - { name: "description", label: "Description", widget: "text" }
      - { name: "status", label: "Status", widget: "select", options: ["In Progress", "Completed", "Planning"] }
      - { name: "start_date", label: "Start Date", widget: "datetime" }
      - { name: "end_date", label: "End Date", widget: "datetime", required: false }
      - { name: "image_url", label: "Project Image", widget: "image", required: false }

  # RACING JOURNEY
  - name: "racing_journey"
    label: "🏁 Racing Journey"
    folder: "data/racing-journey"
    create: true
    slug: "{{id}}"
    fields:
      - { name: "id", label: "ID", widget: "number" }
      - { name: "title", label: "Title", widget: "string" }
      - { name: "description", label: "Description", widget: "text" }
      - { name: "image", label: "Image", widget: "image", required: false }
      - { name: "link", label: "Link", widget: "string", required: false }

  # SPONSORS
  - name: "sponsors"
    label: "🤝 Sponsors"
    folder: "data/sponsors"
    create: true
    slug: "{{id}}"
    fields:
      - { name: "id", label: "ID", widget: "string", hint: "Unique identifier (e.g., spr_2025_001)" }
      - { name: "name", label: "Name", widget: "string" }
      - { name: "logo", label: "Logo", widget: "image", required: false }
      - { name: "tier", label: "Tier", widget: "select", options: ["platinum", "gold", "silver", "bronze", "partner"] }
      - { name: "website", label: "Website", widget: "string", required: false }
      - { name: "description", label: "Description", widget: "text", required: false }
      - { name: "since", label: "Since", widget: "string" }
